version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurant
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - PORT=3000
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=restaurant
      - MYSQL_URL=jdbc:mysql://mysql:3306/restaurant?allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mongodb

volumes:
  mysql-data:
  mongo-data: 