[build]
builder = "nixpacks"
buildCommand = "chmod +x ./mvnw && ./mvnw package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/restaurant-server.jar"
healthcheckPath = "/api/menu"
healthcheckTimeout = 300 